apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: avoid-namespace-default
      namespace: demo-cloudnativeapps
    unsetOnly: true
resources:
- knative-serving.yaml
- knative-eventing.yaml