---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitops-eventing-role-binding
  namespace: knative-serving
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitops-serving-role-binding
  namespace: knative-eventing
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
    name: knative-serving
    namespace: knative-serving
    annotations:
      argocd.argoproj.io/sync-wave: "1"
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
    name: knative-eventing
    namespace: knative-eventing
    annotations:
      argocd.argoproj.io/sync-wave: "1"
---
apiVersion: operator.serverless.openshift.io/v1alpha1
kind: KnativeKafka
metadata:
  name: knative-kafka
  namespace: knative-eventing
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  broker:
    defaultConfig:
      numPartitions: 10
      replicationFactor: 3
      bootstrapServers: my-cluster-kafka-bootstrap.demo-cloudnativeapps.svc:9092
    enabled: true
  channel:
    enabled: true
    bootstrapServers: my-cluster-kafka-bootstrap.demo-cloudnativeapps.svc:9092
  logging:
    level: INFO
  sink:
    enabled: true
  source:
    enabled: true
