apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: builder-pvc
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce