---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: payment
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  lookupPolicy:
    local: false
  tags:
  - name: "latest"
    from:
      kind: DockerImage
      name: quay.io/erivasza0/payment:latest
    referencePolicy:
      type: Source

---
apiVersion: operator.serverless.openshift.io/v1alpha1
kind: KnativeKafka
metadata:
  name: knative-kafka
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  broker:
    defaultConfig:
      numPartitions: 10
      replicationFactor: 3
      bootstrapServers: my-cluster-kafka-bootstrap.demo-cloudnativeapps.svc:9092
    enabled: true
  channel:
    enabled: true
    bootstrapServers: my-cluster-kafka-bootstrap.demo-cloudnativeapps.svc:9092
  logging:
    level: INFO
  sink:
    enabled: true
  source:
    enabled: true

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: payment
  labels:
    app.kubernetes.io/name: payment
    app.kubernetes.io/version: latest
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/demo-cloudnativeapps/payment:latest

---
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  consumerGroup: knative-group
  bootstrapServers:
  - my-cluster-kafka-bootstrap.demo-cloudnativeapps.svc:9092
  topics:
  - orders
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: payment