---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: payments
spec:
  lookupPolicy:
    local: false
  tags:
  - name: "latest"
    from:
      kind: DockerImage
      name: quay.io/erivasza0/payment:latest
    referencePolicy:
      type: Source