---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-distributed-tracing
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  finalizers:
  - kubernetes
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-distributed-tracing
  namespace: openshift-distributed-tracing
  annotations:
    argocd.argoproj.io/sync-wave: "0" 
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger-product
  namespace: openshift-distributed-tracing
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: stable
  name: jaeger-product
  source: redhat-operators 
  sourceNamespace: openshift-marketplace 